name = "UntitledLanguage"
uuid = "e96edc6f-9096-47bc-907c-7cc24c70b7c3"
authors = ["bogdankjastrzebski <bogdan.k.jastrzebski@gmail.com>"]
version = "0.1.0"

[deps]
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"
