syn match agdaFunction "\<ℕ\>"
syn match agdaInfixFunction "\<\*\>\|\<+\>\|\<\^\>"
syn match agdaConstructor "\<suc\>"
syn match agdaFunction "\<_\*_\>\|\<_+_\>\|\<_\^_\>\|\<Set\>"
syn match agdaConstructor "\<zero\>"
syn match agdaFunction "\<Prop\>"
