syn match agdaInfixFunction "\<≡\>"
syn match agdaFunction "\<_≡_\>\|\<Set\>"
syn match agdaConstructor "\<refl\>"
syn match agdaFunction "\<Prop\>"
syn match agdaFunction "\<≡-sym\>"
syn match agdaFunction "\<≡-cong\>"
syn match agdaFunction "\<≡-cong₂\>\|\<≡-cong₃\>\|\<≡-subst\>\|\<≡-trans\>"
syn match agdaFunction "\<≡-cong-app\>"
