syn match agdaFunction "\<ℕ\>"
syn match agdaInfixFunction "\<+\>\|\<≡\>\|\<≤\>"
syn match agdaConstructor "\<suc\>\|\<s≤s\>\|\<z≤n\>"
syn match agdaFunction "\<_+_\>\|\<_≡_\>\|\<_≤_\>\|\<Set\>"
syn match agdaConstructor "\<refl\>\|\<zero\>"
syn match agdaFunction "\<Prop\>\|\<cong\>"
syn match agdaFunction "\<+-comm\>"
syn match agdaFunction "\<+-identityʳ\>"
